### ISSUE TITLE
Incorrect password entered 10 times, max incorrect password limit of 10 reached

### ISSUE THREAD

**Issue by mrbardia72** [hyperledger/fabric-sdk-go#189]
Incorrect password entered 10 times, max incorrect password limit of 10 reached

**Comment by seifghazi** [comment]
Did you end up fixing this issue?

**Comment by mrbardia72** [comment]
> Did you end up fixing this issue?

yes

**Comment by ahsan554** [comment]
I'm facing the same problem. Can you please guide how to solve this?

**Comment by mrbardia72** [comment]
> I'm facing the same problem. Can you please guide how to solve this?

First, you have to go to the file in the path below

network/organizations/fabric-ca/org1/fabric-ca-server.db

Get access and write a code in Golang language that never allows the field in the user table called incorrect_password_attempts to reach 9, otherwise it will be blocked by the filter.

**Comment by aufbakanleitung** [comment]
I also solved this issue by loggin into the (hlf-ca) database and setting the incorrect_password_attempts to 0 (was at 10). I can understand why @mrbardia72 suggests to make sure this field cannot surpass 9 because any time a pipeline uses an old/wrong password it will get to this stage quickly and it's pretty difficult to debug. But preferably the Hyperledger devs would just remove/change this function.

**Comment by mrbardia72** [comment]
How and where did you find this item?
Please help me. Thank you
@aufbakanleitung

**Comment by aufbakanleitung** [comment]
The database used by Hyperledger, called hlf-ca for my project, table users, and then each user has a incorrect_password_attempts field.

**Comment by ravinayag** [comment]
Login to the hlf-ca and install sqllite3 package. For me its `ca-user`, you can change as per yours
Note : take a Backup before any changes
`sqlite3 fabric-ca-server.db`
`sqlite> select *  from users where id='ca-user'`
`sqlite> update users set  incorrect_password_attempts='0'  where id='ca-user';`

**Comment by mrbardia72** [comment]
> Login to the hlf-ca and install sqllite3 package. For me its `ca-user`, you can change as per yours Note : take a Backup before any changes `sqlite3 fabric-ca-server.db` `sqlite> select * from users where id='ca-user'` `sqlite> update users set incorrect_password_attempts='0' where id='ca-user';`

Exactly
This is the solution, I found it a long time ago
