### ISSUE TITLE
Fabric 2.4 support

### ISSUE THREAD

**Issue by Anil8753** [hyperledger/fabric-sdk-go#207]
What is the roadmap to support fabric 2.4 features? Importantly Fabric Gateway service.
Basically, I was looking for the `WithEndorsingOrganizations()` function which is very useful but missing fabric-sdk-go.
This function requires only Orgs MSP Ids whereas the existing `WithEndorsingPeers()` requires the complete peer address.

`WithEndorsingOrganizations()` is available in [fabric-gatway](https://github.com/hyperledger/fabric-gateway)

**Comment by andrew-coleman** [comment]
The Go API for the gateway service is in the repo you linked to in your comment above.  That contains the APIs for all three supported languages (Go, Node & Java).  

An example of  using `WithEndorsingOrganizations()` can be found [here](https://github.com/hyperledger/fabric-gateway/blob/main/samples/go/sample.go#L199).
