### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by realtebo** [hyperledger/fabric-sdk-go#231]
First, let me say you should state if we need to installa sdk as root, as sudoer user, or as normal user.

Anyway, I'm doing all as root by now, because it's first time here for me.

I canno execute this:

    go get github.com/hyperledger/fabric-sdk-go

Becasuse I get 

```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

```

Please update readme

**Comment by werniq** [comment]
Go requires go.mod initialized before installing any dependencies.
Please, run 
`go mod init (some name)` 
and you are ready to work
